# Generated by Django 4.0 on 2022-01-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_discount_order_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-id',)},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
    ]
