# Generated by Django 4.0 on 2022-01-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('is_service', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('created_by', models.CharField(max_length=255)),
                ('updated_by', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
