# Generated by Django 4.0 on 2022-01-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_is_main_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated_on',)},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('-updated_on',)},
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
